class Error:
    def __init__(self, *args):
        self.arr = []

    def my_input(self):
        while True:
            try:
                val = int(input('Введите значения и нажимайте Enter: \n'))
                self.arr.append(val)
                print(f'Текущий список - {self.arr} \n ')
            except:
                print("Неправильный символ, что-то не так с Вашими введеными данными.")
                stop = input('Продолжаем? Напишите stop, если всё: \n')
                if stop != 'stop':
                    print(try_except.my_input())
                else:
                    return f'Программа завершена'


try_except = Error(1)
print(try_except.my_input())